/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ReplacementOutput {
  script: Array<number>
  value: bigint
}
export interface PartialSigData {
  pubkey: Array<number>
  signature: Array<number>
}
export interface Bip32DerivationData {
  pubkey: Array<number>
  fingerprintPath: Array<number>
  child: number
}
export interface PsbtInputData {
  nonWitnessUtxo?: Array<number>
  witnessUtxo?: Array<number>
  partialSigs?: Array<PartialSigData>
  sighashType?: number
  redeemScript?: Array<number>
  witnessScript?: Array<number>
  bip32Derivation?: Array<Bip32DerivationData>
  finalScriptSig?: Array<number>
  finalScriptWitness?: Array<Array<number>>
}
export interface InputPairRequest {
  prevout: Array<number>
  scriptSig: Array<number>
  witness: Array<Array<number>>
  sequence: number
  psbtData: PsbtInputData
}
/**
 * Payjoin URI builder
 * */
export declare class PayjoinUriBuilder {
  constructor(address: string, endpoint: string)
  amount(amountSat: number): PayjoinUriBuilder
  message(message: string): PayjoinUriBuilder
  label(label: string): PayjoinUriBuilder
  disableOutputSubstitution(): PayjoinUriBuilder
  build(): string
}
/**
 * Payjoin URI parser
 * */
export declare class BtcUri {
  constructor(bip21: string)
  assumeChecked(): CheckedBtcUri
}
export declare class CheckedBtcUri {
  checkPjSupported(): PayjoinUri
}
export declare class PayjoinUri {
  endpoint(): PayjoinUrl
}
export declare class PayjoinUrl {
  toString(): string
}
export declare class PayjoinOhttpKeys {
  constructor(bytes: Uint8Array)
  static fetch(ohttpRelay: string, payjoinDirectory: string): Promise<PayjoinOhttpKeys>
  toBytes(): Uint8Array
  static fromBytes(bytes: Uint8Array): PayjoinOhttpKeys
}
export declare class PayjoinRequest {
  url(): string
  body(): Uint8Array
  post(): Uint8Array
  processResponse(response: Uint8Array): PayjoinResponse
}
export declare class PayjoinResponse {
  version(): string
  psbt(): string | null
  v2Context(): PayjoinV2Context | null
}
export declare class PayjoinV2Context {
  extractRequest(ohttpRelay: string): PayjoinRequest
  processResponse(response: Uint8Array, request: PayjoinRequest): string | null
}
export declare class PayjoinSenderBuilder {
  constructor(psbt: string, uri: string)
  disableOutputSubstitution(disable: boolean): this
  buildRecommended(minFeeRateSatPerVb: number): PayjoinSender
  buildWithAdditionalFee(maxFeeContributionSats: number, changeIndex: number | undefined | null, minFeeRateSatPerVb: number, clampFeeContribution: boolean): PayjoinSender
}
export declare class PayjoinSender {
  extractV2(ohttpRelay: string): Promise<PayjoinRequest>
}
export declare class OhttpContext { }
export declare class PayjoinReceiver {
  constructor(address: string, directory: string, ohttpKeys: Uint8Array, ohttpRelay: string, expirySeconds?: bigint | undefined | null)
  pjUrl(): string
  pjUriBuilder(): PayjoinUriBuilder
  extractRequest(): PayjoinRequest
  processResponse(response: Uint8Array, request: PayjoinRequest): UncheckedProposalWrapper | null
}
export declare class UncheckedProposalWrapper {
  originalTx(): string
  checkBroadcastSuitability(minFeeRate: number | undefined | null, canBroadcast: (...args: any[]) => any): MaybeInputsOwnedWrapper
  assumeInteractiveReceiver(): MaybeInputsOwnedWrapper
}
export declare class MaybeInputsOwnedWrapper {
  checkInputsNotOwned(isOwned: (...args: any[]) => any): MaybeInputsSeenWrapper
}
export declare class MaybeInputsSeenWrapper {
  checkNoInputsSeenBefore(isKnown: (...args: any[]) => any): OutputsUnknownWrapper
}
export declare class OutputsUnknownWrapper {
  identifyReceiverOutputs(isReceiverOutput: (...args: any[]) => any): WantsOutputsWrapper
}
export declare class WantsOutputsWrapper {
  isOutputSubstitutionDisabled(): boolean
  substituteReceiverScript(outputScript: Array<number>): WantsOutputsWrapper
  replaceReceiverOutputs(replacementOutputs: Array<ReplacementOutput>, drainScript: Array<number>): WantsOutputsWrapper
  commitOutputs(): WantsInputsWrapper
}
export declare class WantsInputsWrapper {
  tryContributeInputs(candidateInputs: Array<InputPairRequest>): ProvisionalProposalWrapper
}
export declare class ProvisionalProposalWrapper {
  finalizeProposal(walletProcessPsbt: (...args: any[]) => any, minFeerateSatPerVb: number | undefined | null, maxFeerateSatPerVb: number): PayjoinProposalWrapper
}
export declare class PayjoinProposalWrapper {
  utxosToBeLocked(): Array<string>
  isOutputSubstitutionDisabled(): boolean
  psbt(): string
  extractV2Req(): PayjoinRequest
  processRes(response: Array<number>, request: PayjoinRequest): void
}
